address: ':3000'
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: restapp
bundles:
  user:
    fields:
      id:
        type: serial
        primary: true
        index: true
      created:
        type: timestamp
        index: true
      login:
        type: text
        Unique: true
        index: true
      email:
        type: text
        Unique: true
        index: true
