address: ':3000'
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: restapp
bundles:
  node:
    fields:
      id:
        type: serial
        primary: true
      title:
        type: text
      created:
        type: timestamp
      description:
        type: text
        null: true
